### ISSUE TITLE
Honeywell RTH9580WF Thermonstats

### ISSUE THREAD

**Issue by kentinada** [dbarentine/udi-honeywellhome-poly#5]
I have 2 Honeywell RTH9580WF thermostats installed.  The Honeywell Home app corrected imported them both from the Total Comfort Control app but when I log into honeywellhome.com (account created in Honeywell Home app) it says 0 devices were found. Are these thermostats not supported?  Thanks.

**Comment by dbarentine** [comment]
@kentinada I apologize for not being more responsive. Between my day job, some COVID related issues, and now the wildfires in Oregon I have not been paying attention to these projects or the Github notifications for them.

I do not know if those thermostats are supported or not. But if the thermostats you have are not showing up in Honeywell Home your best bet will be to contact Honeywell and figure out why. From the node server standpoint if they don't show up in the Honeywell home website then we can't see them via the API.

**Comment by arrmo** [comment]
Hi,

Just came across this, having a very similar (identical?) issue. My location shows up when I try to authenticate, but no devices (only the location) ... yet my devices show up in the app. Did you have any luck getting this working?

Thanks!

**Comment by dbarentine** [comment]
@arrmo @kentinada I apologize as I've updated this in the UDI forums but forgot to do so here. This is not supported.

Those thermostats I think use Honeywell TCC and Honeywell has removed support for importing those thermostats into Honeywell Home. So the only option for this particular node server is to update to one of the Honeywell Home thermostats such as the T9 or T10.

**Comment by arrmo** [comment]
No worries, and no reason to apologize! Appreciate the follow-up. Thanks!
